### ISSUE TITLE
Link to HOWTO-beta.md isn't working

### ISSUE THREAD

**Issue by tushardave26** [hriordan/PrediXcan#10]
Hello Authors,

I am trying to access the link to HOWTO-beta.md under the software section of the repository. But I am getting 404 (i.e. page not found) error.

Can someone please help me?

Thanks.

Best,
Tushar

**Comment by ScottPDickinson** [comment]
Hi again Tushar,

Sorry for the delay in responding to this (we mostly keep track at hakyimlab/PrediXcan).  Not sure if this has been resolved yet, but I'm having trouble finding this link myself.  If you can still find it, can send us a link to where you found it?

In any case, if my memory serves correctly, this was a first draft of a howto for an update to the software.  It would be irrelevant/out of date now.
