### ISSUE TITLE
correction in documentation

### ISSUE THREAD

**Issue by drveera** [hriordan/PrediXcan#13]
The dosage file format section reads as, "Columns are snpid rsid position allele1 allele2 MAF id1 ..... idn.", where "snpid" is actually the chromosome number (column 1).

**Comment by hakyim** [comment]
@ScottPDickinson could you resolve this please?

**Comment by ScottPDickinson** [comment]
Done.  Thanks!

**Comment by hakyim** [comment]
Thank you @veera-dr and @ScottPDickinson
