### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by drveera** [hriordan/PrediXcan#15]
The default test in Rscript (PrediXcanAssociation.R) is 'linear' and not logistic. 
**the folllowing lines are copied from the script**
# Default TEST_TYPE: linear

if (is.null(argv$TEST_TYPE)) {
  argv$TEST_TYPE <- "linear"
}

**Comment by hakyim** [comment]
@ScottPDickinson could you please correct this?

**Comment by ScottPDickinson** [comment]
Done. Sorry about the error.  The default is linear, and the documentation has been updated accordingly.  Thanks!

**Comment by hakyim** [comment]
Thank you @veera-dr and @ScottPDickinson

**Comment by hakyim** [comment]
Thank you @veera-dr and @ScottPDickinson
