### ISSUE TITLE
Does the genotype build make a difference on prediction??

### ISSUE THREAD

**Issue by gpwhiz** [hriordan/PrediXcan#27]
Hello, I wanted to know if the genotype build makes any difference on the gene expression prediction. My genotype data is on hg18, and I am using GTEx v7 as reference in PrediXcan. Do I need to convert to hg19, then Gh38, and then do the prediction? Will that improve the accuracy of prediction ?? 
I have already done prediction using hg18 genotypes without any errors. Please advise.

**Comment by hakyim** [comment]
Hi

the models in V7 were trained with hg19 so it will work best with that
build. Our models should be robust to using other builds since we are
matching rsids but of course there will be some corner cases where hg19
will do much better.

I hope this helps
Haky
