### ISSUE TITLE
Covariance file flag

### ISSUE THREAD

**Issue by gpwhiz** [hriordan/PrediXcan#32]
Hello, I am interested in conducting the s-predixcan in diverse populations. The DB folder at PredictDB contains covariance file with the .DB files, what flag or option should I be using to include them.
Thank you.

**Comment by Heroico** [comment]
Hi there,

The software in this repository implements only individual-level PrediXcan.

S-PrediXcan is available in this other repositoy:
https://github.com/hakyimlab/MetaXcan

You'll find appropriate examples and documentation therein. The flags are:
```
#db file path
--model_db_path
#ld file path
--covariance
```
