### ISSUE TITLE
Not possible to download DGN Whole Blood LASSO SQLite db file

### ISSUE THREAD

**Issue by cthorball** [hriordan/PrediXcan#7]
Hello, 
When trying to download the DGN Whole Blood LASSO SQLite db file, the following error occurs:
AccessDeniedAccessDenied8E6090A9FEF0A18664M1u8fxfIu5kXhdQtR14J8/J2N7rXgEHAI6r+lxQr860nGCZ8H807uxa7I8boxe

There is no problem with the other files.

**Comment by ScottPDickinson** [comment]
Hi there,

Sorry for the delay in response.  (We mainly keep track of things are hakyimlab/PrediXcan)  The links are working at PredictDB.org.  If you still remember where you got this broken link, can you check that it works now, and if not, send us where you found it?

-Scott
